### PR TITLE
Unit test for search bar #95

### PR DESCRIPTION
**Pull request by Yang8547**
Please check. 
I have Tested on local, result was OK.

### CODE REVIEW

**Comment by Yang8547** [comment]
ERROR is 
`include(../Frontend/include/dbConnector2.php): failed to open stream: No such file or directory`
However, when I test at home, it works. Alex, do you known how to fix it?

**Comment by daniakalomiris** [comment]
@Yang8547 The IP address for the web server was changed which might be causing the error when connecting to the database. @Luigi1000 could you check this because it will affect all subsequent unit tests?

**Comment by daniakalomiris** [comment]
I took a look at dbConnector2.php and the server is connecting to 'localhost' instead of the correct IP address. I will change that and it should fix the error.

**Comment by Yang8547** [comment]
@daniakal I try to use our IP address as the server name, but it still cannot pass Travis check. The error for my code is Travis cannot recognize the directory I wrote.
 I asked Alex this morning, he told me he will modify the Travis config that would solve the file include error and DB connection timeout error

**Pull request closed without merging**
