### PR TITLE
Front end test branch

### PR DESCRIPTION
**Pull request by Yang8547**
Please review.
user profile feature added.
The user can view his account summary, view all ads he has posted and edit his information.
Need **# backend** provide the query to retrieve the data from user table and item table
#25

### CODE REVIEW

**Review by anbochuan — APPROVED** [review]
I just linked it to the homepage, and it works well on my localhost. The other functions will be tested after the DB connection establish.

**Comment by sridath** [comment]
yes!! after the Database connection , other functions can be tested

**Comment by Anitarai** [comment]
Hopefully it will also work well after database connection.

**Comment by Anitarai** [comment]
@yang8547 definitely I will provide you the queries by late night..

**Pull request merged**
